<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_SocialAffiliate
 * @version     0.1.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */

?>
<?php $creditDetails = Mage::getModel('invitefriends/customer')->creditCalculation();?>
    <ul class="invite_my_acc">
            
               <li>
                            <p class="amount"><?php echo $this->__('Total Earned Credits: ').$creditDetails['total_credits'];?></p>
                            <p class="amount"><?php echo $this->__('Upcoming Credits: ').$creditDetails['upcoming_credits'];?></p>
                </li>
                <li>
                            <p class="amount"><?php echo $this->__('Available Credits: ').$creditDetails['balance'];?></p>
                            <p class="amount"><?php echo $this->__('Used Credits: ').$creditDetails['used_credits'];?></p>
                </li>

        
    </ul>