<?php 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_SocialAffiliate
 * @version     0.1.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
?>
    <table id="shopping-cart-totals-table">
        <col />
        <col width="1" />
        <tfoot>
            <?php echo $this->renderTotals('footer'); ?>
    
        </tfoot>
        <tbody>
            <?php echo $this->renderTotals(); ?>
           
        </tbody>
    </table>

    <?php 
   $DiscountAmount = Mage::getModel('invitefriends/transactionhistory')->getDiscountAmount();
   if($DiscountAmount) {
   ?>
    <div class="affiliate_discount"><form method="post" action="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>invitefriends/index/AffiliateCoupon">
        <input style="margin:0 5px;" type="checkbox" name="no_discount" value="1" onclick="this.form.submit();" id="no_discount" <?php $no_discount= Mage::getModel('core/cookie')->get('no_discount'); if(!$no_discount) { echo 'checked="checked"'; } ?> />
    </form>
        <span> <?php echo $this->__('Use Affiliate Discount'); ?> </span></div>
   <?php } ?>