<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_SocialAffiliate
 * @version     0.1.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
?>
<?php $app_key = Mage::helper('invitefriends')->getfbappId();?>
<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js"> </script>

<script type="text/javascript">
    //<![CDATA[
    window.fbAsyncInit = function() {
        FB.init({appId  : '<?php echo $app_key; ?>',
            status : true,
            cookie : true,
            xfbml  : true
        });

        FB.Canvas.setAutoResize(true);

    };

document.observe('click', function(e){
    var target = e.findElement('a[rel^=fbinvite_frnds]') || e.findElement('button[rel^=fbinvite_frnds]');
    if (target && target.readAttribute('rel')=='fbinvite_frnds') {
        e.stop();

        FB.login(function(response_login) {
            if (response_login.authResponse) {                
                FB.api('/me', function(response_auth) {                    
                    FB.ui({method: 'apprequests', message: 'Your friend has requested you to join to explore interesting products that suits you.', data: 'tracking information for the user',filters:['app_non_users','app_users','all']},
                    function(response_invite){
                        send_wall_invitation_init(response_invite,response_auth);
                    });
                })
            }
        });

    }
});
//]]>
</script>
<?php $refferalUrl = Mage::getModel('invitefriends/customer')->getRefferalLink();?>
<script type="text/javascript">
//<![CDATA[
var strRedirectUrl = "<?php echo $_SERVER['REQUEST_URI'];?>";
function send_wall_invitation_init(response_invite,response_auth){
if(response_invite != '' && response_auth != ''){    
    var send_invitation_url = '<?php echo Mage::getBaseUrl(); ?>invitefriends/index/updateFbuserid?fbinvite_request_to='+response_invite.to+'&fbinvite_request_from='+response_auth.id;
    var xmlhttp;
    if (window.XMLHttpRequest)
      {// code for IE7+, Firefox, Chrome, Opera, Safari
      xmlhttp=new XMLHttpRequest();
      }
    else
      {// code for IE6, IE5
      xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
      }
    xmlhttp.onreadystatechange=function()
      {
      if (xmlhttp.readyState==4 && xmlhttp.status==200)
        {
            window.location.href = strRedirectUrl;
        }
      }     
    xmlhttp.open("POST",send_invitation_url,true);
    xmlhttp.send();
}
}
//]]>
</script>